- components/ui/Title.jsx
- pages/_app.js
- pages/index.js
- public/assets/images/rectangle.svg
- styles/globals.css
- tailwind.config.js
- Add title component
- ID: #005
- Link: [Notion](https://www.notion.so/apeunit/sections-Title-component-571cacdb15de4500956ecbd110782984)
- None
> Feat: Title Component

- components/svgs/Arrow.jsx
- components/ui/Button.jsx
- pages/index.js
- styles/globals.css
- tailwind.config.js
Added two versions of the Button component, both default and large versions, with animated arrow.
- ID: 006
- Link:  [Notion](https://www.notion.so/apeunit/Button-Component-7c664707f7ba4930b1375fc30930632b) 
- None
> Feat: Button Component

- components/sections/ContactUs.jsx
- pages/index.js
- tailwind.config.js
This branch develops contact us section on desktop
- ID: #015
- Link: https://www.notion.so/apeunit/Contact-Us-Section-78ab040eebb34187b27a7f6764ec7948
- Contact us responsiveness on other devices
Desktop:
> Feat: Contact us section

- components/sections/Partners.jsx
- data/logos.js
added the links that navigates to partners page
- ID: 023
- Link:[ notion](https://www.notion.so/apeunit/add-links-in-Partners-section-97b4ea16b6e24eb290e0a62ba671ec87)
- None
> Feat: Added Partners Links

- components/sections/ContactUs.jsx
- components/sections/OurWork.jsx
- components/sections/WhoWeAre.jsx
- components/ui/Button.jsx
- data/projects.js
Passing button link in button component as a link
- ID: #024
- Link: https://www.notion.so/apeunit/Fix-Button-directing-link-f74e4ff1648e425191030c532dfbbdd4
- Changing link in href to be passed as a prop
- None
> Fix: Passing Button link as a prop

- components/sections/ContactUs.jsx
Contact us section mobile
- ID: #026
- Link: https://www.notion.so/apeunit/Fix-contact-section-on-mobile-8a961e17e7464883ae923ea5d4ccbcc0
- Contact us section mobile
- None
> Fix: Fixing contact us section on mobile

- components/cards/WhatWeDoCard.jsx
- components/cards/Work.jsx
- components/layout/Footer.jsx
- components/sections/Hero.jsx
- components/sections/JoinOurTeam.jsx
- components/sections/OurWork.jsx
- components/svgs/Arrow.jsx
- components/ui/Anchor.jsx
- components/ui/Headings.jsx
- components/ui/Title.jsx
- components/wrapper/Wrapper.jsx
removed repetitions and spaces that were not needed in the project sections
- ID: 025
- Link:[Notion](https://www.notion.so/apeunit/bugs-in-all-sections-50769cd39b764aeab5a5ee3e08601fc3)
none
> Fix: Remove all Remaining Bugs in the Project

- components/cards/Work.jsx
- components/sections/OurWork.jsx
- components/ui/Button.jsx
- data/projects.js
> Fix: adding links to our work buttons

- components/cards/WhatWeDoCard.jsx
- components/cards/Work.jsx
- components/layout/Footer.jsx
- components/sections/ContactUs.jsx
- components/sections/Hero.jsx
- components/sections/JoinOurTeam.jsx
- components/sections/OurWork.jsx
- components/sections/Partners.jsx
- components/sections/WhatWeDo.jsx
- components/sections/WhoWeAre.jsx
- components/ui/Anchor.jsx
- components/ui/Headings.jsx
- components/ui/Title.jsx
Renaming headings components from H3 to Heading3 etc...
- ID: #043
- Link: https://www.notion.so/apeunit/Fix-Headings-file-e3dfbc2ba62e41488f2855243f17b373
- None
> Refactor: Renaming heading components 

- components/sections/ContactUs.jsx
Removing <br> and formating file
- ID: #031
- Link: https://www.notion.so/apeunit/Fix-Contact-Section-4023b5551b994179985ffbb72dd1acc1
- None
> Refactor: Refactoring contact us section 

- components/cards/WhatWeDoCard.jsx
Renamed the component to match the file name, removed unnecessary template string, and used a ternary operator instead of lengthy `if..else`
- ID: 028
- Link: [Notion](https://www.notion.so/apeunit/Fix-What-We-Do-Card-ec77ad4407b3440f8cbf6c0d9fd3bd2f)
- None
> Refactor: What We Do Card

- components/layout/Footer.jsx
- data/socialMedias.js
- Rename anchor data to social media since they are all social media
- ID: #037
- Link: [Notion](https://www.notion.so/apeunit/Fix-Anchor-data-file-202636ee74324ead8b7e1fcf4047ea83)
- None
> Refactor: Anchor data file

- components/wrappers/PageWrapper.jsx
- pages/index.js
Renaming file and folder
- ID: #034
- Link: https://www.notion.so/apeunit/Fix-Wrapper-10d99d67e7834628aedebe0d49327162
- None
> Refactor: Renaming wrapper folder and file

- components/cards/Work.jsx
- components/sections/ContactUs.jsx
- components/sections/OurWork.jsx
- components/sections/WhoWeAre.jsx
- components/ui/Button.jsx
- Fixed the import data path
- Instead of using `directLink` prop, I used `redirectLink`
- Fixed The prop `imageSrc2` is a bit confusing. Remove the 2 at the end.
- ID: #029
- Link: [Notion](https://www.notion.so/apeunit/Fix-Work-Card-322814a7cb014bde9b429aa9ed620321)
- None
> Refactor: our work card component

- pages/index.js
- Remove the empty closing tags. Remove fragments
- Use ES6,
- ID: 044
- Link: [Notion](https://www.notion.so/apeunit/Fix-Index-page-File-d0cc22fbc2994e73a4b83dc353d683ee)
- None
> refactor: use ES6 in index file

- components/cards/Work.jsx
Use self closing tags when needed in work section
- ID: 046
- Link: [Notion](https://www.notion.so/apeunit/Fix-Self-closing-tags-5039904898894908a1b558f759fd4929)
- None
> Refactor: Self closing Tags

- pages/_document.js
- styles/globals.css
> Refactor: Global css file

- package.json
- Rename the app name in `package.json`
- ID: #039
- Link: [Notion](https://www.notion.so/apeunit/Fix-Package-json-eca2b9ffa80248fca495c8b686782555)
- None
> Refactor: Add application name 

- components/sections/JoinOurTeam.jsx
- data/openings.js
Properly indented the data and exported the data using default export.
- ID: 038
- Link: [Notion](https://www.notion.so/apeunit/Fix-Openings-data-file-616932dc87de49d7913a4c9161ff5a5d)
- None
> Refactor: Openings Data File

- components/layout/Footer.jsx
- components/sections/JoinOurTeam.jsx
- components/sections/OurWork.jsx
- components/sections/Partners.jsx
- data/logos.js
Used more descriptive names for the map arguments and kept the second argument as `index` to avoid confusion
- ID: #030
- Link: [Notion](https://www.notion.so/apeunit/Fix-Map-parameters-7cd52db9ca4f4cdda4499f011f96e3c2)
- None
> Refactor: Map Parameters

- components/sections/JoinOurTeam.jsx
- components/svgs/Arrow.jsx
- components/svgs/WhiteArrow.jsx
- components/ui/Button.jsx
- Separate arrow components into different files
- ID: #045
- Link: [Notion](https://www.notion.so/apeunit/Fix-Arrow-components-54bc0719889b4106a2b3c97958a74fb2)
- None
> Refactor: Separate Arrow components

- components/cards/Work.jsx
- components/sections/Hero.jsx
- components/sections/JoinOurTeam.jsx
- components/ui/Headings.jsx
- components/ui/Title.jsx
- components/ui/buttons/DefaultButton.jsx
- components/ui/buttons/LargeButton.jsx
Added spacing between button text and arrow on mobile screen of the default button
- ID: 049
- Link: [Notion](https://www.notion.so/apeunit/Fix-Button-mobile-6e3f50451ff140208a853ace6e4bb9cc)
- None
> Fix: Added gap to default button on mobile

- components/sections/OurWork.jsx
- Remove unnecessary curly braces
- ID: 
- Link: 
- None
> Refactor: Remove unecessary currly braces

- .gitignore
- components/sections/ContactUs.jsx
- components/sections/WhoWeAre.jsx
- components/ui/buttons/LargeButton.jsx
- Remove unnecessary `vercel` in `.gitignore file`.
- Remove unnecessary template strings in button components.
- ID: 
- Link: 
- None
> Refactor: Remove typos in both buttons and contact section

- components/cards/Work.jsx
- components/layout/Footer.jsx
- components/sections/OurWork.jsx
- components/ui/buttons/LargeButton.jsx
- components/wrappers/PageWrapper.jsx
- tailwind.config.js
added spacings in our work section and footer section
- ID: 
- Link: 
- None
> fix: added spacing in footer section and our work

- data/logos.js
- data/projects.js
- Update unit 8 project live link
- Update unit 8 logo link
- ID: 60
- Link: [Notion](https://www.notion.so/apeunit/HofFix-Unit-8-live-link-8cfc6170f8c74294affa334d4ff6a853)
- None
> Feat: Unit 8 live link

- components/sections/Hero.jsx
> Feat: testing deployment

- components/cards/Work.jsx
- components/sections/Hero.jsx
- Projects screenshots to links
- ID: 
- Link: 
- None
> Fix: Project screenshots

- components/sections/JoinOurTeam.jsx
- data/openings.js
Removed existing openings and added a new opening. Also, wrapped opening with a Link to open an external link
- ID: 
- Link: 
- None
> Fix: Update the listing in Join our Team section

- components/sections/Hero.jsx
- Fix the hero section underline width
- ID: 
- Link: 
- None
> Fix: Hero section underline width

- components/cards/WhatWeDoCard.jsx
- components/sections/OurWork.jsx
- Improve the typography styles of what we do section
- Improve the spacing between our work cards
- ID: 70
- Link: https://www.notion.so/apeunit/Fix-What-we-do-section-text-content-a6de40a5745e4adf9d33ed7e9238a378?pvs=4
- None
> Fix: What we do section typography

- components/sections/Hero.jsx
- components/sections/JoinOurTeam.jsx
- components/sections/Partners.jsx
- components/sections/WhoWeAre.jsx
- components/ui/Title.jsx
- components/ui/Typography.jsx
- tailwind.config.js
remove the title background and the underline on the blockchain technology
- ID: 069
- Link: [Notion](https://www.notion.so/apeunit/hotfix-remove-title-background-35b950943a5d402ca3d97922eb63f943?pvs=4)
- None
> fix: remove title background and blockchain technology underline

- components/sections/Hero.jsx
- components/sections/JoinOurTeam.jsx
- data/openings.js
Updated JoinOurTeam listing with new information.
- ID: 
- Link: 
- None
> Feat: JoinOurTeam listing

- components/cards/Work.jsx
- components/sections/OurWork.jsx
- components/wrappers/PageWrapper.jsx
- tailwind.config.js
- Fix wrapper size on screens of  `1280px`
- ID: 075
- Link: [Notion](https://www.notion.so/apeunit/wrapper-on-device-of-width-1280px-681ec7e917af40c091cd8ad602c0864e?pvs=4)
- None
> Fix: wrapper 

- components/cards/Work.jsx
- Fix the border-radius of work card on mobile devices
- ID: 
- Link: 
- None
> Fix: Work card border radius

- components/cards/WhatWeDoCard.jsx
- package-lock.json
- package.json
- ID: 077
- Link: [Notion](https://www.notion.so/apeunit/Fix-WhatWeDoCard-component-87d43088be884f71877ad80348344b50?pvs=4)
- None
> Refactor: What we do card component

- components/cards/WhatWeDoCard.jsx
- components/cards/Work.jsx
- components/sections/OurWork.jsx
- components/sections/Partners.jsx
- data/logos.js
- data/offers.js
- data/projects.js
- Fix the order of class names and conditionally rendered class names.
- Add dynamic image alt.
- ID:  #78 
- Link: [Notion](https://www.notion.so/apeunit/Refactor-Work-component-0ae475389f3348a4a0fa490108864a9f?pvs=4)
- None
> Fix: Work component

- components/sections/Hero.jsx
- components/sections/Partners.jsx
> fix: reduce margin on the hero section paragraph
